### PR TITLE
[rpm] fix BuildRequires for opensuse

### PR DESCRIPTION
**Pull request by fabbione**
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

### CODE REVIEW

**Review by ondrejmular — APPROVED** [review]

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please (fixing CI here)

**Comment by fabbione** [comment]
retest this please (fixing CI here)

**Comment by fabbione** [comment]
@ondrejmular please merge this PR when it fits you.

The original problem is pacemaker-libs-devel having a different name on OpenSuse as seen in those 2 logs:

Pre-fix
https://ci.kronosnet.org/view/pcs/job/pcs-build-rpms/420/pcs-build-rpms=opensuse-tumbleweed-x86-64/console
12:51:41 error: Failed build dependencies:
12:51:41 	pacemaker-libs-devel >= 2.1.0 is needed by pcs-0.11.1-1.x86_64
12:51:41 make: *** [Makefile:1286: rpm] Error 11

Post-fix
https://ci.kronosnet.org/view/pcs/job/pcs-build-rpms/421/pcs-build-rpms=opensuse-tumbleweed-x86-64/console

post-fix will still fail to build on Opensuse because python3.9 is not default yet and it´s not shipping some of the rpm macros required to set python3_sitelib correctly on the OS.

I have temporary disabled the OpenSuse rpm build to allow CI to move forward. pcs-build-nonvoting still builds pcs tho, so that will give us enough coverage while they complete the transition.

**Pull request merged**
