### PR TITLE
Add date detection function to the date constraint rule

### PR DESCRIPTION
**Pull request by daaitudian**
Hi:
When using the 'pcs constraint rule add <constraint id> score=<score> date gt|lt <date> ' command , date could be used any value. This pr mainly adds a date validation.

### CODE REVIEW

**Comment by daaitudian** [comment]
Hi:
I see that this pr has not been passed, and I want to know how I can modify the current problem. Looking forward to your reply!

**Comment by tomjelinek** [comment]
Hi @daaitudian,

We appreciate the effort you invested in this PR. Unfortunately, the pcs team have been rather busy lately. We haven't had a chance to do a full review of your patch. I'm sorry about that. Please, bear with us, we will post feedback here.

**Review by tomjelinek — CHANGES_REQUESTED** [review]
We appreciate your effort. However, this PR cannot be accepted in its current form. Apart from the issues mentioned in code, there are no added tests for the new code and the patch doesn't pass our test suite:
```
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/root/git/pcs/pcs_test/tier1/legacy/test_rule.py", line 1076, in test_node_attr_integer_not_date_expression
    self.fixture_has_integer(["date", "gt", "integer", "123"])
  File "/root/git/pcs/pcs_test/tier1/legacy/test_rule.py", line 1003, in fixture_has_integer
    return rule.has_node_attr_expr_with_type_integer(
  File "/root/git/pcs/pcs/rule.py", line 310, in has_node_attr_expr_with_type_integer
    and rule_tree.children[1].is_not_iso_date()
  File "/root/git/pcs/pcs/rule.py", line 352, in is_not_iso_date
    result=datetime.fromisoformat(self.value)
AttributeError: 'symbol_integer' object has no attribute 'value'
```

Your proposed solution doesn't really fit to the architecture. The date validation should be implemented in a manner similar to `pcs.rule.SymbolTernaryInRange.left_denotation`.

**Comment by daaitudian** [comment]
Thanks for the reminder that I will modify it later.

**Pull request closed without merging**
