### PR TITLE
pcsd: use childprocess gem instead of open4 (Closes: #552)

### PR DESCRIPTION
**Pull request by lucaskanashiro**
The open4 gem is unmaintained upstream for a while, the last activity in its git repository is from 2014. On the other hand, the childprocess maintenance is more active recently, and it also used by some other projects written in ruby, like vagrant and selenium-webdriver.

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
FWIW I tested this patch in the test suite we use in Ubuntu and all tests passed just fine. Here is the test suite:

https://github.com/canonical/server-test-scripts/tree/main/ha/virsh

**Comment by ondrejmular** [comment]
test this please

**Comment by lucaskanashiro** [comment]
Thanks for triggering the tests @ondrejmular . I noticed the failures in `debian-testing`, `debian11` and `ubuntu-22-04-lts`, all of them are failing because of this:

```
configure: error: ruby gem childprocess not found
```

With the proposed patch, `childprocess` needs to be installed during configure time (instead of `open4`). I am wondering where is the code executed in your CI system, because it is installing `open4` instead of `childprocess`, and there is no occurrence of `open4` in the proposed branch. My guess is that this is hosted somewhere else and it needs update. Could you please clarify that to me?

**Review by tomjelinek — APPROVED** [review]
Thank you very much for this patch. It's just perfect. Once the CI issue is resolved, we're going to merge it.

**Comment by lucaskanashiro** [comment]
Thank you very much @tomjelinek ! Waiting for that :)

**Comment by tomjelinek** [comment]
retest this please

**Comment by tomjelinek** [comment]
retest this please

**Comment by tomjelinek** [comment]
retest this please

**Pull request merged**
