### PR TITLE
booth: Check whether path '/etc/booth' exists

### PR DESCRIPTION
**Pull request by daaitudian**
Hi:
I added a check before the error of opening the booth.key, which can be avoid the '/etc/booth/booth.key' error if the booth is not installed.

[booth] pcs booth setup shall not jump to report "No such file or directory: '/etc/booth/booth.key'" when /etc/booth doesn't exist #225

### CODE REVIEW

**Comment by daaitudian** [comment]
ok to test

**Comment by tomjelinek** [comment]
test this please

**Comment by tomjelinek** [comment]
retest this please

**Comment by tomjelinek** [comment]
Hi @daaitudian, thank you very much for the pull request. Excellent job finding your way through pcs code base! I did a few minor fixes and will merge the patch once it passes CI.

**Comment by tomjelinek** [comment]
test this please

**Review by tomjelinek — APPROVED** [review]

**Comment by daaitudian** [comment]
Hi @tomjelinek ,Thank you so much for your help, especially those that I didn't notice. This has helped me a lot.

**Pull request merged**
