### PR TITLE
[test] enable parallel testing

### PR DESCRIPTION
**Pull request by fabbione**
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

### CODE REVIEW

**Review by ondrejmular — CHANGES_REQUESTED** [review]
`parallel_tests_requirements.txt` is missing in `EXTRA_DIST` in Makefile.am. Otherwise it looks good to me.

I'll update gitlab CI to use `--enable-parallel-tests` later.

**Comment by ondrejmular** [comment]
Actually, I’m going to fix this right away and use the feature in gitlab CI as well.

**Comment by fabbione** [comment]
@ondrejmular Makefile.am fixed. I would like a successful run in CI before we add or change more things

**Comment by fabbione** [comment]
retest this please

**Pull request merged**
