### PR TITLE
Disallow setting order constraints on resources within a group

### PR DESCRIPTION
**Pull request by F16shen**
Found an Issue when sets constraint on resources within a group:
I have a two node cluster and resources like this:
```
  * Resource Group: test:
    * dummy1	(ocf:pacemaker:Dummy):	 Started node1
    * dummy2	(ocf:pacemaker:Dummy):	 Started node1
    * dummy3	(ocf:pacemaker:Dummy):	 Started node1
```
and  set an order constraint for dummy3 dummy1
`
  pcs constraint order set dummy3 dummy1
`
It seems ok, but when I tried to move the group to another node, pcs reports error below
```
[root@node1 pcs]# pcs resource move test node2
Error: Unable to simulate changes in CIB: Transition failed: terminated
An invalid transition was produced
```
It looks like pacemaker doesn't allow this operation, but pcs has no warning about it(it really confused me until I delete that order constraint).Since resources in a group have their on boot sequence define by their position in the group, perhaps it's better to stop user set order constraint for them.

for now I still some complie issue unresolved, I thike it needs to modify tests but I'm not quite sure how to do it.
```
ERROR: pcs_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object '_FailedTest' has no attribute 'pcs_test'

======================================================================
ERROR: test_returns_export_of_found_elements (pcs_test.tier0.lib.commands.test_constraint_common.ConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pcs/BUILD/pcs-0.10.12/pcs_test/tier0/lib/commands/test_constraint_common.py", line 198, in test_returns_export_of_found_elements
    {"ids": ["A", "B"], "options": {"role": "Master"}},
  File "/root/pcs/BUILD/pcs-0.10.12/pcs_test/tier0/lib/commands/test_constraint_common.py", line 190, in create
    {"id": "some_id", "symmetrical": "true"},
  File "/root/pcs/BUILD/pcs-0.10.12/pcs/lib/commands/constraint/common.py", line 48, in create_with_set
    resource_set.is_resource_in_group(resource_set_item['ids'], cib)
  File "/root/pcs/BUILD/pcs-0.10.12/pcs/lib/cib/constraint/resource_set.py", line 97, in is_resource_in_group
    resource_section = get_resources(cib)
  File "/root/pcs/BUILD/pcs-0.10.12/pcs/lib/cib/tools.py", line 457, in get_resources
    return sections.get(tree, sections.RESOURCES)
  File "/root/pcs/BUILD/pcs-0.10.12/pcs/lib/cib/sections.py", line 61, in get
    reports.messages.CibCannotFindMandatorySection(section_name)
pcs.lib.errors.LibraryError: ReportItem(severity=ReportItemSeverity(level='ERROR', force_code=None), message=CibCannotFindMandatorySection(section='configuration/resources'), context=None)

```

Thanks

### CODE REVIEW

**Comment by tomjelinek** [comment]
test this please

**Comment by tomjelinek** [comment]
test this please

**Comment by F16shen** [comment]
Hi @tomjelinek ,
I have some problem when I try to get cib in `resource_set.is_resource_in_same_group`, when I import `utils.py` in `resource_set.py` it will cause a circular import in test.
I also tried to get cib when `pcs.lib.cib.constraint.constraint.create_with_set` is called, It also cause other test failed.
So now I only import it in `resource_set.is_resource_in_same_group`, is there a better way to do this?

**Comment by tomjelinek** [comment]
test this please

**Comment by F16shen** [comment]
Thanks, this really help me a lot

**Comment by tomjelinek** [comment]
test this please

**Comment by tomjelinek** [comment]
retest this please

**Review by tomjelinek — APPROVED** [review]

**Comment by tomjelinek** [comment]
retest this please

**Pull request merged**
