### PR TITLE
Reenable ci builds

### PR DESCRIPTION
**Pull request by fabbione**

### CODE REVIEW

**Comment by fabbione** [comment]
This PR obsoletes https://github.com/ClusterLabs/pcs/pull/895

commit 1: allows to generically specify a random version of python for rpm build. No exceptions
commit 2: enables CI workarounds specifically

This PR needs to land after: https://github.com/kronosnet/ci-tools/commit/edc0dec73b20eda45d0bfb4f5463eb4373f72479

**Comment by fabbione** [comment]
retest this please

**Review by mirecheck — APPROVED** [review]

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Pull request merged**
