### PR TITLE
Replace pyopenssl

### PR DESCRIPTION
**Pull request by tomjelinek**

### CODE REVIEW

**Comment by tomjelinek** [comment]
retest this please

**Comment by ondrejmular** [comment]
retest this please

**Review by ondrejmular — APPROVED** [review]

**Comment by fabbione** [comment]
retest this please
(there was a timeout in CI)

**Comment by fabbione** [comment]
As a side note, when changing dependencies, CI needs to be updated to reflect those changes, specially if a new module is required.

**Pull request merged**
