### PR TITLE
validate booth ticket

### PR DESCRIPTION
**Pull request by tomjelinek**

### CODE REVIEW

**Review by ondrejmular — APPROVED** [review]

**Comment by tomjelinek** [comment]
retest this please

**Comment by tomjelinek** [comment]
retest this please

**Comment by tomjelinek** [comment]
retest this please

**Comment by tomjelinek** [comment]
retest this please

**Comment by tomjelinek** [comment]
retest this please

**Comment by tomjelinek** [comment]
retest this please

**Pull request merged**
