### PR TITLE
rpm: use new package name for pacemaker devel on opensuse

### PR DESCRIPTION
**Pull request by fabbione**
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

### CODE REVIEW

**Comment by fabbione** [comment]
As a piece of information, we are doing some major builder rework in CI. It is very likely that the rpm build job will fail. This patch is required to fix the whole thing.

**Review by idevat — APPROVED** [review]

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please
(fixing ci bits and pieces)

**Comment by fabbione** [comment]
retest this
(hopefully the last round)

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Pull request merged**
